ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "metaOAuthToken" TEXT;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "metaOAuthExpiresAt" TIMESTAMP(3);
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "metaConnectedAt" TIMESTAMP(3);
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "metaBusinessId" TEXT;

ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "googleOAuthAccessToken" TEXT;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "googleOAuthRefreshToken" TEXT;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "googleOAuthExpiresAt" TIMESTAMP(3);
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "googleConnectedAt" TIMESTAMP(3);
